# Makurai Mage Theme
# Default colors
[colors.primary]
background = '#15161B'
foreground = '#FFFFFF'

# Normal colors
[colors.normal]
black = '#000000'
red = '#FF5555'
green = '#95FB79'
yellow = '#FFEE99'
blue = '#82AAFF'
magenta = '#D2A6FF'
cyan = '#82AAFF'
white = '#FFFFFF'

# Bright colors
[colors.bright]
black = '#000000'
red = '#FF5555'
green = '#95FB79'
yellow = '#FFEE99'
blue = '#82AAFF'
magenta = '#D2A6FF'
cyan = '#82AAFF'
white = '#FFFFFF'

[cursor]
text = '#000000'
cursor = '#ffdb29'