# Makurai Healer Theme
# Default colors
[colors.primary]
background = '#F5F5F5'
foreground = '#0A0A0A'

# Normal colors
[colors.normal]
black = '#000000'
red = '#CC0000'
green = '#2B7F3A'
yellow = '#8D6E15'
blue = '#1A4B8D'
magenta = '#6A3889'
cyan = '#1A4B8D'
white = '#0A0A0A'

# Bright colors
[colors.bright]
black = '#000000'
red = '#CC0000'
green = '#2B7F3A'
yellow = '#8D6E15'
blue = '#1A4B8D'
magenta = '#6A3889'
cyan = '#1A4B8D'
white = '#0A0A0A'

[cursor]
text = '#000000'
cursor = '#D4A017'