# Makurai Warrior Theme
# Default colors
[colors.primary]
background = '#14161f'
foreground = '#FFFFFF'

# Normal colors
[colors.normal]
black = '#24292e'
red = '#FF5555'
green = '#98eb7a'
yellow = '#789CEA'
blue = '#F4C367'
magenta = '#FF875F'
cyan = '#F4C367'
white = '#FFFFFF'

# Bright colors
[colors.bright]
black = '#2e3339'
red = '#ff5d5d'
green = '#a7ff86'
yellow = '#84abff'
blue = '#ffd671'
magenta = '#ffd671'
cyan = '#ffd671'
white = '#ffffff'

# Dim colors
[colors.dim]
black = '#1b1e22'
red = '#e54c4c'
green = '#88d36d'
yellow = '#6c8cd2'
blue = '#dbaf5c'
magenta = '#dbaf5c'
cyan = '#dbaf5c'
white = '#e5e5e5'

[colors.cursor]
text = '#000000'
cursor = '#ffdb29'