# Makurai Warrior Theme
# Default colors
[colors.primary]
background = '#14161f'
foreground = '#FFFFFF'

# Normal colors
[colors.normal]
black = '#2e3339'
red = '#FF5555'
green = '#98eb7a'
yellow = '#F4C367'
blue = '#789CEA'
magenta = '#dc74ed'
cyan = '#789CEA'
white = '#FFFFFF'

# Bright colors
[colors.bright]
black = '#49525c'
red = '#ff5d5d'
green = '#a7ff86'
yellow = '#ffd671'
blue = '#84abff'
magenta = '#f27fff'
cyan = '#84abff'
white = '#ffffff'

# Dim colors
[colors.dim]
black = '#1b1e22'
red = '#e54c4c'
green = '#88d36d'
yellow = '#dbaf5c'
blue = '#6c8cd2'
magenta = '#c668d5'
cyan = '#6c8cd2'
white = '#e5e5e5'

[colors.cursor]
text = '#000000'
cursor = '#ffdb29'