# Makurai Warrior Theme
# Default colors
[colors.primary]
background = '#15161B'
foreground = '#FFFFFF'

# Normal colors
[colors.normal]
black = '#2e3339'
red = '#ff5f5f'
green = '#92c468'
yellow = '#F4C367'
blue = '#a8ceba'
magenta = '#D2A6FF'
cyan = '#a8ceba'
white = '#FFFFFF'

# Bright colors
[colors.bright]
black = '#49525c'
red = '#ff6868'
green = '#a0d772'
yellow = '#ffd671'
blue = '#b8e2cc'
magenta = '#e7b6ff'
cyan = '#b8e2cc'
white = '#ffffff'

# Dim colors
[colors.dim]
black = '#1b1e22'
red = '#e55555'
green = '#83b05d'
yellow = '#dbaf5c'
blue = '#97b9a7'
magenta = '#bd95e5'
cyan = '#97b9a7'
white = '#e5e5e5'

[colors.cursor]
text = '#000000'
cursor = '#ffdb29'