# Makurai Warrior Theme for Rio Terminal

[colors]
# Background and foreground
background = '#15161B'
foreground = '#FFFFFF'

# Cursor colors
cursor = '#ffdb29'
cursor-foreground = '#000000'

# Selection colors
selection-background = '#264F78'
selection-foreground = '#ffffff'

# Normal colors (0-7)
black = '#2e3339'
red = '#ff5f5f'
green = '#92c468'
yellow = '#F4C367'
blue = '#a8ceba'
magenta = '#D2A6FF'
cyan = '#a8ceba'
white = '#FFFFFF'

# Bright colors (8-15)
bright-black = '#49525c'
bright-red = '#ff6868'
bright-green = '#a0d772'
bright-yellow = '#ffd671'
bright-blue = '#b8e2cc'
bright-magenta = '#e7b6ff'
bright-cyan = '#b8e2cc'
bright-white = '#ffffff'

# Dim colors
dim-black = '#1b1e22'
dim-red = '#e55555'
dim-green = '#83b05d'
dim-yellow = '#dbaf5c'
dim-blue = '#97b9a7'
dim-magenta = '#bd95e5'
dim-cyan = '#97b9a7'
dim-white = '#e5e5e5'