# Makurai Warrior Theme for Rio Terminal

[colors]
# Background and foreground
background = '#14161f'
foreground = '#FFFFFF'

# Cursor colors
cursor = '#ffdb29'
cursor-foreground = '#000000'

# Selection colors
selection-background = '#264F78'
selection-foreground = '#ffffff'

# Normal colors (0-7)
black = '#2e3339'
red = '#FF5555'
green = '#98eb7a'
yellow = '#F4C367'
blue = '#789CEA'
magenta = '#dc74ed'
cyan = '#789CEA'
white = '#FFFFFF'

# Bright colors (8-15)
bright-black = '#49525c'
bright-red = '#ff5d5d'
bright-green = '#a7ff86'
bright-yellow = '#ffd671'
bright-blue = '#84abff'
bright-magenta = '#f27fff'
bright-cyan = '#84abff'
bright-white = '#ffffff'

# Dim colors
dim-black = '#1b1e22'
dim-red = '#e54c4c'
dim-green = '#88d36d'
dim-yellow = '#dbaf5c'
dim-blue = '#6c8cd2'
dim-magenta = '#c668d5'
dim-cyan = '#6c8cd2'
dim-white = '#e5e5e5'