# Makurai Spring Theme
# Default colors
[colors.primary]
background = '#15161B'
foreground = '#FFFFFF'

# Normal colors
[colors.normal]
black = '#2e3339'
red = '#FF5555'
green = '#D4FF59'
yellow = '#FFB347'
blue = '#66E6FF'
magenta = '#D2A6FF'
cyan = '#66E6FF'
white = '#FFFFFF'

# Bright colors
[colors.bright]
black = '#49525c'
red = '#ff5d5d'
green = '#e9ff61'
yellow = '#ffc44e'
blue = '#70fdff'
magenta = '#e7b6ff'
cyan = '#70fdff'
white = '#ffffff'

# Dim colors
[colors.dim]
black = '#1b1e22'
red = '#e54c4c'
green = '#bee550'
yellow = '#e5a13f'
blue = '#5bcfe5'
magenta = '#bd95e5'
cyan = '#5bcfe5'
white = '#e5e5e5'

[colors.cursor]
text = '#000000'
cursor = '#ffdb29'