# Makurai Spring Theme for Rio Terminal

[colors]
# Background and foreground
background = '#15161B'
foreground = '#FFFFFF'

# Cursor colors
cursor = '#ffdb29'
cursor-foreground = '#000000'

# Selection colors
selection-background = '#264F78'
selection-foreground = '#ffffff'

# Normal colors (0-7)
black = '#2e3339'
red = '#FF5555'
green = '#D4FF59'
yellow = '#FFB347'
blue = '#66E6FF'
magenta = '#D2A6FF'
cyan = '#66E6FF'
white = '#FFFFFF'

# Bright colors (8-15)
bright-black = '#49525c'
bright-red = '#ff5d5d'
bright-green = '#e9ff61'
bright-yellow = '#ffc44e'
bright-blue = '#70fdff'
bright-magenta = '#e7b6ff'
bright-cyan = '#70fdff'
bright-white = '#ffffff'

# Dim colors
dim-black = '#1b1e22'
dim-red = '#e54c4c'
dim-green = '#bee550'
dim-yellow = '#e5a13f'
dim-blue = '#5bcfe5'
dim-magenta = '#bd95e5'
dim-cyan = '#5bcfe5'
dim-white = '#e5e5e5'