# Default colors
[colors.primary]
background = '#F0F0F0'
foreground = '#000000'

# Normal colors
[colors.normal]
black = '#000000'
red = '#FF0000'
green = '#008F11'
yellow = '#FF7D00'
blue = '#0066FF'
magenta = '#00A8F0'
cyan = '#0066FF'
white = '#000000'

# Bright colors
[colors.bright]
black = '#000000'
red = '#FF0000'
green = '#008F11'
yellow = '#FF7D00'
blue = '#0066FF'
magenta = '#00A8F0'
cyan = '#0066FF'
white = '#000000'

[cursor]
text = '#000000'
cursor = '#000000'