# Makurai Light Theme
# Default colors
[colors.primary]
background = '#f8f8fc'
foreground = '#323640'

# Normal colors
[colors.normal]
black = '#505053'
red = '#CC0000'
green = '#51A150'
yellow = '#976700'
blue = '#3D76F3'
magenta = '#AB31A9'
cyan = '#3D76F3'
white = '#323640'

# Bright colors
[colors.bright]
black = '#808085'
red = '#e00000'
green = '#59b158'
yellow = '#a67100'
blue = '#4381ff'
magenta = '#bc35b9'
cyan = '#4381ff'
white = '#373b46'

# Dim colors
[colors.dim]
black = '#303032'
red = '#b70000'
green = '#489048'
yellow = '#875c00'
blue = '#366ada'
magenta = '#992c98'
cyan = '#366ada'
white = '#2d3039'

[colors.cursor]
text = '#000000'
cursor = '#D4A017'