# Makurai Light Theme
# Default colors
[colors.primary]
background = '#f8f8fc'
foreground = '#2D3748'

# Normal colors
[colors.normal]
black = '#7c7c7d'
red = '#DC143C'
green = '#2E8B57'
yellow = '#D2691E'
blue = '#1E90FF'
magenta = '#8A2BE2'
cyan = '#1E90FF'
white = '#586c8d'

# Bright colors
[colors.bright]
black = '#c6c7c8'
red = '#f21642'
green = '#32985f'
yellow = '#e77321'
blue = '#219eff'
magenta = '#972ff8'
cyan = '#219eff'
white = '#60769b'

# Dim colors
[colors.dim]
black = '#4a4a4b'
red = '#c61236'
green = '#297d4e'
yellow = '#bd5e1b'
blue = '#1b81e5'
magenta = '#7c26cb'
cyan = '#1b81e5'
white = '#4f617e'

[colors.cursor]
text = '#000000'
cursor = '#D4A017'