# Makurai Light Theme for Rio Terminal

[colors]
# Background and foreground
background = '#f8f8fc'
foreground = '#586c8d'

# Cursor colors
cursor = '#D4A017'
cursor-foreground = '#000000'

# Selection colors
selection-background = '#C6DBFF'
selection-foreground = '#2D3748'

# Normal colors (0-7)
black = '#7c7c7d'
red = '#DC143C'
green = '#2E8B57'
yellow = '#D2691E'
blue = '#1E90FF'
magenta = '#8A2BE2'
cyan = '#1E90FF'
white = '#586c8d'

# Bright colors (8-15)
bright-black = '#c6c7c8'
bright-red = '#f21642'
bright-green = '#32985f'
bright-yellow = '#e77321'
bright-blue = '#219eff'
bright-magenta = '#972ff8'
bright-cyan = '#219eff'
bright-white = '#60769b'

# Dim colors
dim-black = '#4a4a4b'
dim-red = '#c61236'
dim-green = '#297d4e'
dim-yellow = '#bd5e1b'
dim-blue = '#1b81e5'
dim-magenta = '#7c26cb'
dim-cyan = '#1b81e5'
dim-white = '#4f617e'