# Default colors
[colors.primary]
background = '#15161B'
foreground = '#e8e8ea'

# Normal colors
[colors.normal]
black = '#000000'
red = '#FF5555'
green = '#92c468'
yellow = '#9d9eb0'
blue = '#8e8e90'
magenta = '#FF7733'
cyan = '#8e8e90'
white = '#e8e8ea'

# Bright colors
[colors.bright]
black = '#000000'
red = '#FF5555'
green = '#92c468'
yellow = '#9d9eb0'
blue = '#8e8e90'
magenta = '#FF7733'
cyan = '#8e8e90'
white = '#e8e8ea'

[cursor]
text = '#000000'
cursor = '#ffdb29'