# Makurai Rogue Theme
# Default colors
[colors.primary]
background = '#15161B'
foreground = '#e8e8ea'

# Normal colors
[colors.normal]
black = '#24292e'
red = '#FF5555'
green = '#92c468'
yellow = '#9d9eb0'
blue = '#8e8e90'
magenta = '#FF875F'
cyan = '#8e8e90'
white = '#e8e8ea'

# Bright colors
[colors.bright]
black = '#2e3339'
red = '#ff5d5d'
green = '#a0d772'
yellow = '#acadc1'
blue = '#9c9c9e'
magenta = '#ff9468'
cyan = '#9c9c9e'
white = '#ffffff'

# Dim colors
[colors.dim]
black = '#1b1e22'
red = '#e54c4c'
green = '#83b05d'
yellow = '#8d8e9e'
blue = '#7f7f81'
magenta = '#e57955'
cyan = '#7f7f81'
white = '#d0d0d2'

[colors.cursor]
text = '#000000'
cursor = '#ffdb29'