# Makurai Rogue Theme
# Default colors
[colors.primary]
background = '#15161B'
foreground = '#e8e8ea'

# Normal colors
[colors.normal]
black = '#24292e'
red = '#FF5555'
green = '#92c468'
yellow = '#95A4C6'
blue = '#C4873A'
magenta = '#FF875F'
cyan = '#C4873A'
white = '#e8e8ea'

# Bright colors
[colors.bright]
black = '#2e3339'
red = '#ff5d5d'
green = '#a0d772'
yellow = '#a3b4d9'
blue = '#d7943f'
magenta = '#ff9468'
cyan = '#d7943f'
white = '#ffffff'

# Dim colors
[colors.dim]
black = '#1b1e22'
red = '#e54c4c'
green = '#83b05d'
yellow = '#8693b2'
blue = '#b07934'
magenta = '#e57955'
cyan = '#b07934'
white = '#d0d0d2'

[colors.cursor]
text = '#000000'
cursor = '#ffdb29'