# Makurai Rogue Theme
# Default colors
[colors.primary]
background = '#15161B'
foreground = '#e8e8ea'

# Normal colors
[colors.normal]
black = '#2e3339'
red = '#FF5555'
green = '#92c468'
yellow = '#f7e254'
blue = '#94A3C5'
magenta = '#978ebe'
cyan = '#94A3C5'
white = '#e8e8ea'

# Bright colors
[colors.bright]
black = '#49525c'
red = '#ff5d5d'
green = '#a0d772'
yellow = '#fff85c'
blue = '#a2b3d8'
magenta = '#a69cd1'
cyan = '#a2b3d8'
white = '#ffffff'

# Dim colors
[colors.dim]
black = '#1b1e22'
red = '#e54c4c'
green = '#83b05d'
yellow = '#decb4b'
blue = '#8592b1'
magenta = '#877fab'
cyan = '#8592b1'
white = '#d0d0d2'

[colors.cursor]
text = '#000000'
cursor = '#ffdb29'