# Makurai Rogue Theme for Rio Terminal

[colors]
# Background and foreground
background = '#15161B'
foreground = '#e8e8ea'

# Cursor colors
cursor = '#ffdb29'
cursor-foreground = '#000000'

# Selection colors
selection-background = '#264F78'
selection-foreground = '#ffffff'

# Normal colors (0-7)
black = '#2e3339'
red = '#FF5555'
green = '#92c468'
yellow = '#f7e254'
blue = '#94A3C5'
magenta = '#978ebe'
cyan = '#94A3C5'
white = '#e8e8ea'

# Bright colors (8-15)
bright-black = '#49525c'
bright-red = '#ff5d5d'
bright-green = '#a0d772'
bright-yellow = '#fff85c'
bright-blue = '#a2b3d8'
bright-magenta = '#a69cd1'
bright-cyan = '#a2b3d8'
bright-white = '#ffffff'

# Dim colors
dim-black = '#1b1e22'
dim-red = '#e54c4c'
dim-green = '#83b05d'
dim-yellow = '#decb4b'
dim-blue = '#8592b1'
dim-magenta = '#877fab'
dim-cyan = '#8592b1'
dim-white = '#d0d0d2'