# Makurai Rogue Theme for Rio Terminal

[colors]
# Background and foreground
background = '#15161B'
foreground = '#e8e8ea'

# Cursor colors
cursor = '#ffdb29'
cursor-foreground = '#000000'

# Selection colors
selection-background = '#264F78'
selection-foreground = '#ffffff'

# Normal colors (0-7)
black = '#24292e'
red = '#FF5555'
green = '#92c468'
yellow = '#95A4C6'
blue = '#C4873A'
magenta = '#FF875F'
cyan = '#C4873A'
white = '#e8e8ea'

# Bright colors (8-15)
bright-black = '#2e3339'
bright-red = '#ff5d5d'
bright-green = '#a0d772'
bright-yellow = '#a3b4d9'
bright-blue = '#d7943f'
bright-magenta = '#ff9468'
bright-cyan = '#d7943f'
bright-white = '#ffffff'

# Dim colors
dim-black = '#1b1e22'
dim-red = '#e54c4c'
dim-green = '#83b05d'
dim-yellow = '#8693b2'
dim-blue = '#b07934'
dim-magenta = '#e57955'
dim-cyan = '#b07934'
dim-white = '#d0d0d2'