# Makurai Autumn Theme
# Default colors
[colors.primary]
background = '#15161B'
foreground = '#FFFFFF'

# Normal colors
[colors.normal]
black = '#2e3339'
red = '#fc4c4c'
green = '#a1cd32'
yellow = '#fac25a'
blue = '#4FC8C8'
magenta = '#FF6B9D'
cyan = '#4FC8C8'
white = '#FFFFFF'

# Bright colors
[colors.bright]
black = '#49525c'
red = '#ff5353'
green = '#b1e137'
yellow = '#ffd563'
blue = '#56dcdc'
magenta = '#ff75ac'
cyan = '#56dcdc'
white = '#ffffff'

# Dim colors
[colors.dim]
black = '#1b1e22'
red = '#e24444'
green = '#90b82d'
yellow = '#e1ae51'
blue = '#47b4b4'
magenta = '#e5608d'
cyan = '#47b4b4'
white = '#e5e5e5'

[colors.cursor]
text = '#000000'
cursor = '#ffdb29'