# Makurai Autumn Theme for Rio Terminal

[colors]
# Background and foreground
background = '#15161B'
foreground = '#FFFFFF'

# Cursor colors
cursor = '#ffdb29'
cursor-foreground = '#000000'

# Selection colors
selection-background = '#602c3d'
selection-foreground = '#ffffff'

# Normal colors (0-7)
black = '#2e3339'
red = '#fc4c4c'
green = '#a2d93d'
yellow = '#facc75'
blue = '#60bfbf'
magenta = '#e67399'
cyan = '#60bfbf'
white = '#FFFFFF'

# Bright colors (8-15)
bright-black = '#49525c'
bright-red = '#ff5353'
bright-green = '#b2ee43'
bright-yellow = '#ffe080'
bright-blue = '#69d2d2'
bright-magenta = '#fd7ea8'
bright-cyan = '#69d2d2'
bright-white = '#ffffff'

# Dim colors
dim-black = '#1b1e22'
dim-red = '#e24444'
dim-green = '#91c336'
dim-yellow = '#e1b769'
dim-blue = '#56abab'
dim-magenta = '#cf6789'
dim-cyan = '#56abab'
dim-white = '#e5e5e5'