# Makurai Autumn Theme for Rio Terminal

[colors]
# Background and foreground
background = '#15161B'
foreground = '#FFFFFF'

# Cursor colors
cursor = '#ffdb29'
cursor-foreground = '#000000'

# Selection colors
selection-background = '#602c3d'
selection-foreground = '#ffffff'

# Normal colors (0-7)
black = '#2e3339'
red = '#fc4c4c'
green = '#a1cd32'
yellow = '#fac25a'
blue = '#4FC8C8'
magenta = '#FF6B9D'
cyan = '#4FC8C8'
white = '#FFFFFF'

# Bright colors (8-15)
bright-black = '#49525c'
bright-red = '#ff5353'
bright-green = '#b1e137'
bright-yellow = '#ffd563'
bright-blue = '#56dcdc'
bright-magenta = '#ff75ac'
bright-cyan = '#56dcdc'
bright-white = '#ffffff'

# Dim colors
dim-black = '#1b1e22'
dim-red = '#e24444'
dim-green = '#90b82d'
dim-yellow = '#e1ae51'
dim-blue = '#47b4b4'
dim-magenta = '#e5608d'
dim-cyan = '#47b4b4'
dim-white = '#e5e5e5'